package GUI;

import java.awt.*;
import javax.swing.*;
import Model.*;
import java.io.File;
import java.util.ArrayList;

/**
 * 
 * @author  OGO 1.2 groep 1
 *          Carl van Dueren den Hollander
 *          Ferry
 *          Nicky Advokaat
 *          Roby Visser
 *          Tim v Dalen
 */
public class MainFrame extends javax.swing.JFrame {
    private InputPanel inputPanel;
    private OutputPanel outputPanel;
    private Input input;
    private Output output;
    private FileReader filereader;
    private Algorithm algorithm;
    private static int size = 30; // size of point drawn at screen
    private JFileChooser fileChooser = new JFileChooser();

    /** Creates new form MainFrame */
    public MainFrame() {
        filereader = new FileReader();
        algorithm = new Algorithm();
        
        input = new Input( 0, 0, new ArrayList< Point >() );
        output = algorithm.Algorithm1(input);
                
        FileChooserSetup();
        
        initComponents();
        initAddedComponents();
    }
    
    /**
     * initializes "open file" menu
     */
    private void FileChooserSetup(){
        fileChooser.setCurrentDirectory(new java.io.File("C:/Users/s104595/Documents/NetBeansProjects/PuzzleSolver"));
        fileChooser.setDialogTitle("open een puzzeltje");
        fileChooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        fileChooser.setAcceptAllFileFilterUsed(false);

        // filter .txt files only
        javax.swing.filechooser.FileFilter filter = (javax.swing.filechooser.FileFilter) new txtFileFilter();
        fileChooser.addChoosableFileFilter((javax.swing.filechooser.FileFilter) filter);
    }
    
    // manually added methods
    // initialize and place all added components
    private void initAddedComponents() {        
        inputPanel = new InputPanel();
        inputPanel.setSize(jPanel1.getWidth(), jPanel1.getHeight());
        jPanel1.add(inputPanel);
        
        outputPanel = new OutputPanel();
        outputPanel.setSize(jPanel2.getWidth(), jPanel2.getHeight());
        jPanel2.add(outputPanel);
    }
    
    private class InputPanel extends JPanel  {

        public InputPanel(){
            this.setBackground(Color.white);
        }
        
        @Override
        public void paintComponent(Graphics g) {
            super.paintComponent(g);
            for( Point p : input.points ){
                g.setColor(Color.blue);
                //g.fillRect(p.x * size, p.y * size, size, size
                g.fillOval(p.x * 2 * size, p.y * 2 * size, size, size);
            }
            g.setColor(Color.red);
            g.drawString("Clusters: " + input.nrOfClusters + "    Points: " + input.nrOfPoints, 0, 10);
        }

    }
    
    private class OutputPanel extends JPanel  {

        public OutputPanel(){
            this.setBackground(Color.white);
        }
        
        @Override
        public void paintComponent(Graphics g) {
            super.paintComponent(g);
            for( ClusterPoint p : output.clusterPoints ){
                g.setColor( getColor(p.cluster) );
                g.fillOval(p.point.x * 2 * size, p.point.y * 2 * size, size, size);
            }
            g.setColor(Color.red);
            g.drawString("Clusters: " + output.nrOfClusters + "    Points: " + output.nrOfPoints, 0, 10);
        }
        
        private Color getColor(int cluster){
            switch(cluster){
                case 1: return Color.RED; 
                case 2: return Color.BLUE;    
                case 3: return Color.GREEN;
                case 4: return Color.YELLOW;
                case 5: return Color.PINK;
                case 6: return Color.ORANGE;
                case 7: return Color.MAGENTA;    
                default: return Color.GRAY;    
            }
        }

    }
    
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSlider1 = new javax.swing.JSlider();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cluster Finder");
        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 655, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 597, Short.MAX_VALUE)
        );

        jSlider1.setMajorTickSpacing(5);
        jSlider1.setMaximum(30);
        jSlider1.setMinimum(5);
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 631, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 597, Short.MAX_VALUE)
        );

        jButton1.setText("Open File");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4" }));

        jLabel2.setText("Algorithm:");

        jLabel3.setText("Size:");

        jButton2.setText("Run");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextField1.setText("No File Selected");
        jTextField1.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * 
     * slider changes size of drawn clusters 
     */
    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        // TODO add your handling code here:
        size = jSlider1.getValue();
        jPanel1.repaint();
        jPanel2.repaint();
    }//GEN-LAST:event_jSlider1StateChanged

    /**
     * takes care "open file" can only open .txt files
     */
    class txtFileFilter extends javax.swing.filechooser.FileFilter {
        public boolean accept(File f) {
            return f.isDirectory() || f.getName().toLowerCase().endsWith(".txt");
        }

        public String getDescription() {
            return ".txt files";
        }
    }
    
    /** 
     * Open File button 
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int retval = fileChooser.showOpenDialog(null);  // open menu op locatie null
        if (retval == JFileChooser.APPROVE_OPTION) {            
            File file = fileChooser.getSelectedFile();
            input = filereader.readFromFile(file.getName());    // read new file   
            jTextField1.setText(file.getName());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Run();
    }//GEN-LAST:event_jButton2ActionPerformed

    
    private void Run(){
        switch(Integer.parseInt(jComboBox1.getSelectedItem().toString())){
                case 1: output = algorithm.Algorithm1(input); break;
                case 2: output = algorithm.Algorithm2(input); break;
                case 3: output = algorithm.Algorithm3(input); break;
                case 4: output = algorithm.Algorithm4(input); break;    
            }            
            initAddedComponents();
            repaint();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
